# Generated by Django 4.2.11 on 2026-03-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record. Auto-generated UUID.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created. Set by server, never editable.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of last modification. Updated automatically on every save.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(help_text="ICH month number. e.g. 0, 3, 6, 12."),
                ),
                (
                    "scheduled_date",
                    models.DateField(help_text="Exact date this test point is due."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When all results for this test point were submitted.",
                        null=True,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_points",
                        to="batches.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schedule_test_point",
                "ordering": ["month"],
                "indexes": [
                    models.Index(fields=["status"], name="schedule_te_status_2014b4_idx"),
                    models.Index(fields=["scheduled_date"], name="schedule_te_schedul_cb83ea_idx"),
                ],
                "unique_together": {("batch", "month")},
            },
        ),
    ]
