# Generated by Django 4.2.11 on 2026-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpoint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("overdue", "Overdue"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("pulled", "Pulled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
