# Generated by Django 4.2.11 on 2026-03-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record. Auto-generated UUID.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created. Set by server, never editable.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of last modification. Updated automatically on every save.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft delete flag. False means logically deleted. Record is never hard-deleted.",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="e.g. AMX-2024-001. Must be globally unique.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("mfg_date", models.DateField(help_text="Manufacturing date.")),
                ("expiry_date", models.DateField(help_text="Expiry date of the batch.")),
                (
                    "incubation_date",
                    models.DateField(
                        help_text="Date batch was placed in stability chamber. Must be >= mfg_date."
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        choices=[("long_term", "Long Study"), ("accelerated", "Accelerated Study")],
                        help_text="ICH study type — determines which test points are generated.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("shelf", models.CharField(max_length=50)),
                ("rack", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=50)),
                (
                    "qty_placed",
                    models.PositiveIntegerField(help_text="Total quantity placed in chamber."),
                ),
                (
                    "qty_remaining",
                    models.PositiveIntegerField(help_text="Quantity remaining after sample pulls."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "batches_batch",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["batch_number"], name="batches_bat_batch_n_7e8a40_idx"),
                    models.Index(fields=["status"], name="batches_bat_status_7a0087_idx"),
                    models.Index(fields=["study_type"], name="batches_bat_study_t_55d2e9_idx"),
                ],
            },
        ),
    ]
