# Generated by Django 4.2.11 on 2026-03-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("SIGN", "Electronic Signature"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the model that was changed. e.g. Batch, TestResult",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="UUID of the record that was changed.", max_length=100
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        help_text="Human-readable representation of the record at time of change.",
                        max_length=255,
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="State of the record before the change.", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="State of the record after the change.", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Exact server time when this action occurred. Never editable.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional context about why this change was made."
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id"], name="audit_log_model_n_c04ad8_idx"
                    ),
                    models.Index(fields=["performed_by"], name="audit_log_perform_a3668d_idx"),
                    models.Index(fields=["timestamp"], name="audit_log_timesta_e8e14e_idx"),
                ],
            },
        ),
    ]
